#This config is to set the default value of the flags
#Note: command line args can override these value
output = "" #use "" to represent no output file, output directed to stdout
tokens = false
recent = false
line_numbers = false
dirs_only = false

# This is a list of directory names to exclude from the output.
exclude_dirs = ["__pycache__", "venv", ".git"]